// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJqW4QgEpEUXOY9IqX40t7UtZkpo9v9Mg',
    appId: '1:1029869106896:web:f4ed3ee40b04c7adea90d5',
    messagingSenderId: '1029869106896',
    projectId: 'everybite-ba3f2',
    authDomain: 'everybite-ba3f2.firebaseapp.com',
    storageBucket: 'everybite-ba3f2.firebasestorage.app',
    measurementId: 'G-FX1MF7NHP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQFZ4mEKCOB1Ed1PFC_PPueS3rcT1fFgw',
    appId: '1:1029869106896:android:a2cf1c7f0e2afc29ea90d5',
    messagingSenderId: '1029869106896',
    projectId: 'everybite-ba3f2',
    storageBucket: 'everybite-ba3f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpG3p74HkcQ5S7SW3OMyPkPrBunMIP3Rk',
    appId: '1:1029869106896:ios:679d33f71d51792dea90d5',
    messagingSenderId: '1029869106896',
    projectId: 'everybite-ba3f2',
    storageBucket: 'everybite-ba3f2.firebasestorage.app',
    iosBundleId: 'com.example.everybite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpG3p74HkcQ5S7SW3OMyPkPrBunMIP3Rk',
    appId: '1:1029869106896:ios:679d33f71d51792dea90d5',
    messagingSenderId: '1029869106896',
    projectId: 'everybite-ba3f2',
    storageBucket: 'everybite-ba3f2.firebasestorage.app',
    iosBundleId: 'com.example.everybite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJqW4QgEpEUXOY9IqX40t7UtZkpo9v9Mg',
    appId: '1:1029869106896:web:c9fff6463bb25742ea90d5',
    messagingSenderId: '1029869106896',
    projectId: 'everybite-ba3f2',
    authDomain: 'everybite-ba3f2.firebaseapp.com',
    storageBucket: 'everybite-ba3f2.firebasestorage.app',
    measurementId: 'G-Z9MRN1T9VR',
  );

}